["pyproject.toml".tool.black]
line-length = 79

[[".pre-commit-config.yaml".repos]]
yaml = """
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.7.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==19.10b0]
"""
