[nitpick.files.absent]
".isort.cfg" = "Move values to setup.cfg, section [isort]"
".flake8" = "Move values to setup.cfg, section [flake8]"
"mypy.ini" = "Move values to setup.cfg, section [mypy]"

[nitpick.files.present]
"README.md" = "A project should have `README.md`"
".gitignore" = "A project should have `.gitignore` file"
"setup.cfg" = "A project should have `setup.cfg` file"
