name: code-style

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        requirements: ['minimal', 'latest']
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set minimal dependencies
        if: matrix.requirements == 'minimal'
        run: |
          python -c "req = open('./requirements.txt').read().replace('>', '=') ; open('./requirements.txt', 'w').write(req)"

#      - name: get pip cache dir
#        id: pip-cache
#        run: |
#          python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"
#
#      - name: cache pip
#        uses: actions/cache@v2
#        with:
#          path: ${{ steps.pip-cache.outputs.dir }}
#          key: ${{ runner.os }}-${{ matrix.python-version }}-pip -${{ hashFiles('./requirements/requirements.txt') }} -${{ hashFiles('./requirements/requirements-dev.txt') }}
#          restore-keys: |
#            ${{ runner.os }}-${{ matrix.python-version }}-pip-
#
#      - name: cache pip contrib
#        uses: actions/cache@v2
#        with:
#          path: ${{ steps.pip-cache.outputs.dir }}
#          key: ${{ runner.os }}-${{ matrix.python-version }}-pip -${{ hashFiles('./requirements/requirements-cv.txt') }} -${{ hashFiles('./requirements/requirements-hydra.txt') }} -${{ hashFiles('./requirements/requirements-ml.txt') }} -${{ hashFiles('./requirements/requirements-optuna.txt') }} -${{ hashFiles('./requirements/requirements-mlflow.txt') }} -${{ hashFiles('./requirements/requirements-nifti.txt') }}
#          restore-keys: |
#            ${{ runner.os }}-${{ matrix.python-version }}-pip-contrib
#
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -e .

      - name: Check code-style
        run: |
          catalyst-check-codestyle

      - name: Check dependencies compatibility
        run: |
          pip check
